### ISSUE TITLE
Training code

### ISSUE THREAD

**Issue by WUMINGCHAzero** [Doubiiu/DynamiCrafter#1]
Congratulation on the wonderful work! The results are amazing!
I wonder if you have any plan to release the training code? (If there is a plan, could you tell me the approximate time?)

Thanks for your great work!

**Comment by Doubiiu** [comment]
Hi~ Thanks for your interest. Currently we don't have any plan to release the training code, but personally, I think it is easy to implement that based on the image training code from [SD](https://github.com/Stability-AI/stablediffusion). Thanks for your interest again.

**Comment by WUMINGCHAzero** [comment]
Thanks for your response : )

**Comment by Doubiiu** [comment]
Hi. I find the open-source code from [MotionCtrl](https://github.com/TencentARC/MotionCtrl) and [LVDM](https://github.com/YingqingHe/LVDM) may contain nearly-complete applicable training code for our DynamiCrafter (I think those code can be used with a minor modification)!

**Comment by Doubiiu** [comment]
The training code is available now! @WUMINGCHAzero
