### ISSUE TITLE
Questions about interpolation

### ISSUE THREAD

**Issue by volcverse** [Doubiiu/DynamiCrafter#104]
Hello, thanks for the great work!

I noticed that there are some inconsistencies between the training and inference phases of interpolation. During training, the first and last c_concat are set to the start and end frames respectively, while the rest are set to 0. However, during inference, the first half of c_concat and the second half of c_concat are set to the start and end frames respectively. Does this inconsistency affect the results? Why not unify the training and inference processes?

Any response will be greatly appreciated!

**Comment by Doubiiu** [comment]
Hi I think the training and inference performance are consistent as "the first and last c_concat are set to the start and end frames respectively, while the rest are set to 0." Can you point out the code for "the first half of c_concat and the second half of c_concat are set to the start and end frames respectively". Thanks! Not sure if there is a bug/typo.

**Comment by volcverse** [comment]
Hi there, thanks for your timely response!

I dig deeper into the inference process and found that there are indeed only the first and last frame are used.

[Here](https://github.com/Doubiiu/DynamiCrafter/blob/463d1a0f40f33b76676e2068ca0118e74e8335df/scripts/evaluation/inference.py#L94) is the code that "the first half of c_concat and the second half of c_concat are set to the start and end frames respectively". I check the entire inference. Yes, the training and inference performance are indeed consistent :)

Again, thanks for sharing the great work!
