### ISSUE TITLE
Is the license available for commercial use?

### ISSUE THREAD

**Issue by teenaxta** [Doubiiu/DynamiCrafter#107]
So bit of a confusion here regarding the license. 
The repo has a apache 2.0 license while the [huggingface](https://huggingface.co/Doubiiu/DynamiCrafter_1024) listing says the following

> We develop this repository for RESEARCH purposes, so it can only be used for personal/research/non-commercial purposes.

So, can this model be used for commercial license or not? If not then why may i know what is covered under apache 2.0 license ?

**Comment by Doubiiu** [comment]
Sure, the disclaimer is out-of-date; we have updated it to a standard Apache 2.0 license. Feel free to use it.
