### ISSUE TITLE
Location of the input image in the generated video

### ISSUE THREAD

**Issue by wren93** [Doubiiu/DynamiCrafter#11]
Hi, is there a way to control the location of the input image in the generated video? e.g. if it is possible to always make it the first frame? I tried to look at the code and it seems that the input image is replicated 16 times and concatenated along the channel dimension of the noise, and it seems that there is no way to control it. I am wondering if this is the correct understanding. Thank you!

**Comment by Doubiiu** [comment]
Hi. You understanding is correct. We are studying how to add more controllability.
