### ISSUE TITLE
Does this run on free GPU of google colab?

### ISSUE THREAD

**Issue by Rajesh90123** [Doubiiu/DynamiCrafter#125]
I ran the scripts in google colab by cloning the github  file.
```
from google.colab import drive
drive.mount('/content/drive')
!git clone https://github.com/Doubiiu/DynamiCrafter.git
%cd DynamiCrafter
!pip install -r requirements.txt  #Downloaded pre-trained model and saved it in following way: DynamiCrafter/checkpoints/dynamicrafter_512_interp_v1/model.ckpt
!bash scripts/run_application.sh interp
```
And it gave me following output:
AE working on z of shape (1, 4, 32, 32) = 4096 dimensions.
scripts/run_application.sh: line 47:  7914 Killed  

Is it because of memory and resources constraints? I really loved this project over FILM, so i wanted to test if I could use it in colab like I used FILM.

**Comment by Doubiiu** [comment]
To be honest, I'm not sure about this. Maybe Pro is needed for colab, like mentioned in [here](https://github.com/camenduru/DynamiCrafter-colab).

**Comment by Rajesh90123** [comment]
Thanks 🙏🙏🙏
