### ISSUE TITLE
can this be more GPU efficient? the smallest model requires 20GB

### ISSUE THREAD

**Issue by ninjasaid2k** [Doubiiu/DynamiCrafter#13]

**Comment by Doubiiu** [comment]
Yes. The current implementation does not include the engineering advancement to improve the efficiency and we will try to improve that. Meanwhile we hope our community can help to achieve high efficiency together.
BTW, we will also provide online discord demo later soon.

**Comment by shirubei** [comment]
> Yes. The current implementation does not include the engineering advancement to improve the efficiency and we will try to improve that. Meanwhile we hope our community can help to achieve high efficiency together. BTW, we will also provide online discord demo later soon.

Thank you for this wonderful work. 
Just have a 11GB Graphic card and would like to hear any info on quantization model. Thanks.
