### ISSUE TITLE
Could it run on a single RTX4090 GPU?

### ISSUE THREAD

**Issue by easycodesniper-afk** [Doubiiu/DynamiCrafter#16]
I'm sorry but I only have one GPU with 24G memory...

**Comment by Doubiiu** [comment]
Hi, I have tried running the code on Hugging face A10G large (24G VRAM) and it works. You can have a try on that. We will also release more online demo UI / resources very soon. Thanks for your interest!

**Comment by easycodesniper-afk** [comment]
> Hi, I have tried running the code on Hugging face A10G large (24G VRAM) and it works. You can have a try on that. We will also release more online demo UI / resources very soon. Thanks for your interest!

Got it

**Comment by Doubiiu** [comment]
@easycodesniper-afk Thanks to the report by [ngc-shj](https://github.com/ngc-shj) in #18 , there should be no problem to run it on RTX4090 with 24G GPU Memory, at least for 512 and 256. I think 1024 is also OK.
