### ISSUE TITLE
"perframe_ae" was not specified when calling with resolution 512 from gradio_app.py

### ISSUE THREAD

**Issue by ngc-shj** [Doubiiu/DynamiCrafter#18]
Great work! 

When I checked the code in run.sh and run_mp.sh, the "perframe_ae" option was specified when the resolution was other than 256, i.e. 512 and 1024. However, "perframe_ae" is not set at resolution 512 because only the values from the config file are applied when invoking from gradio_app.py.

I think adding "perframe_ae: True" to inference_512_v1.0.yaml is a good idea. What do you think?

**Comment by Doubiiu** [comment]
yes. i was aware of this when releasing code. But actually `perframe_ae=True` won't bring any benefits in terms of saving GPU memory based on my own attempt. Sure you can add that in the config.

**Comment by ngc-shj** [comment]
Thank you for you replying.

In my environment, RTX 4090 24GB, CPU offload occurred in DynamiCrafter512 model.
Immediately after starting gradio_app.py, 12.8GB of VRAM was used, and after that, memory was used up to 37.2GB (vram 23.6 + mem 13.6).
Setting `perframe_ae=True` did not use more than 12.8GB of VRAM. The time required to generate a video has also been reduced from 120.51 seconds to 53.26 seconds.

**Comment by Doubiiu** [comment]
wow Thanks! I will add that into the config of 512 model.

**Comment by ngc-shj** [comment]
FYI.
For, RTX 4090 Laptop GPU (16GB)
- 1024 model: CUDA OOM occurred
- 512 model: 12.6GB、102.69 sec  `perframe_ae: True`
- 256 model: 11.8GB、46.48 sec `perframe_ae: True`

**Comment by Doubiiu** [comment]
Thanks for your contribution!🙏 @ngc-shj

**Comment by rajatanand86** [comment]
where to add this ? perframe_ae=True
