### ISSUE TITLE
Generated video is hole black

### ISSUE THREAD

**Issue by howardgriffin** [Doubiiu/DynamiCrafter#2]
Hi，When I used run the gradio_app, I got the hole black video out. What's wrong?

**Comment by Doubiiu** [comment]
Hi, is there any error message printed in the standard output console?

**Comment by howardgriffin** [comment]
There was no error log. BTW, when I run the scripts/run.sh, everything was fine.

**Comment by Doubiiu** [comment]
Also can you run the demo using the command line? Not sure if there is any environment setup issue.

**Comment by howardgriffin** [comment]
Here is my console log:
`Global seed set to 111
start: girl talking and blinking 2023-12-05 11:52:47
/usr/local/lib/python3.10/dist-packages/torchvision/transforms/functional.py:1603: UserWarning: The default value of the antialias parameter of all the resizing transforms (Resize(), RandomResizedCrop(), etc.) will change from None to True in v0.17, in order to be consistent across the PIL and Tensor backends. To suppress this warning, directly pass antialias=True (recommended, future default), antialias=None (current default, which means False for Tensors and True for PIL), or antialias=False (only works on Tensors - PIL will still use antialiasing). This also applies if you are using the inference transforms from the models weights: update the call to weights.transforms(antialias=True).
  warnings.warn(
Saved in girl_talking_and_blinking. Time used: 46.71 seconds`

**Comment by Doubiiu** [comment]
I just tested the local gradio demo without any problem. Not sure the error is related to this torchvision.transforms warning and it is so weird. May be need to print the input tensor and output tensor from the network. I guess there may be some issues during saving? Since the model won't predict all black results. Sorry for the inconvenience caused.

**Comment by howardgriffin** [comment]
Really strange. 
When I debugged the code by using gradio_app,  I found that the output video tensor was a normal value, but when I saved the video with torchvision, it turned black. （However, the script method saves the video normally.）
Finnally,I rewrote the way I saved the video to make sure the code was running properly.

**Comment by Doubiiu** [comment]
Glad to here that you have solved it. Would you mind sharing the modified code of saving videos (should be the function `save_videos` in the `scripts/gradio/i2v_test.py`)? It may help someone else in the future, thanks very much!

**Comment by howardgriffin** [comment]
I just replace this line with the following 3 lines:[
        torchvision.io.write_video(savepath, grid, fps=fps, video_codec='h264', options={'crf': '10'})](https://github.com/Doubiiu/DynamiCrafter/blob/b7b2897df38bcb79a7c20aa71c9beddaef88f0ea/scripts/evaluation/funcs.py#L197C69-L197C69) 
`import imageio`      
`grid_list = [i.squeeze().numpy() for i in list(torch.split(grid,1))]`
`imageio.mimsave(savepath, grid_list, fps=fps)`

**Comment by Doubiiu** [comment]
Well-noted. Thanks a lot!

**Comment by Laidawang** [comment]
image2video.get_image(image, test_prompt, steps=24, cfg_scale=7.5, eta=1.0, fs=10, seed=124)
my params
