### ISSUE TITLE
gray stripes in both side of the frame using image to create video

### ISSUE THREAD

**Issue by shirubei** [Doubiiu/DynamiCrafter#27]
Hello, thanks for your great job and open source.
Just created 2s video from  1152*832 image with a 2080Ti  22GB VR, using 560s. 

The motion part is perfect, but sometimes imperfection can be found like fames in this video.
Two gray stripes in both side of the frame. 
Original image: 
![2wandering](https://github.com/Doubiiu/DynamiCrafter/assets/37259748/8be16110-80dd-4197-a84d-edadff673d34)

[https://github.com/Doubiiu/DynamiCrafter/assets/37259748/7559553c-507b-4c63-b62a-77f219edae70](https://github.com/Doubiiu/DynamiCrafter/assets/37259748/7559553c-507b-4c63-b62a-77f219edae70)

And one more question, can I create more longer videos? such as 3s or 4s.
Finally, I have change the format of H264 to H265 just by modified func.py for H264 videos look like still images (no motion effect）
So maybe you can make video format as a parameter that can be set in the config file.

**Comment by shirubei** [comment]
thanks for your rapid response. Apreciate your nice wok!

>Could you share your code? I will add that parameter to the config.

I didn't modify a lot. just hard coded .

Change last line of save_videos in func.py
def save_videos(batch_tensors, savedir, filenames, fps=10):
        ......
        torchvision.io.write_video(savepath, grid, fps=fps, video_codec='h264', options={'crf': '10'})

=>           torchvision.io.write_video(savepath, grid, fps=fps, video_codec='h265', options={'crf': '10'})

**Comment by alexandrtsk** [comment]
shirubei
 Hi friend, please tell me how did you run on 2080, I used comfy ui on 3090 and couldn't run the 1024*576 model because of cuda out of memory error.

**Comment by shirubei** [comment]
> shirubei
> Hi friend, please tell me how did you run on 2080, I used comfy ui on 3090 and couldn't run the 1024*576 model because of cuda out of memory error.

Cause I have a special 2080Ti with 22GB memory.

**Comment by alexandrtsk** [comment]
The 3090 has 24gb of memory, but it doesn't work. Can you explain how and what you installed ? Maybe there is a video tutorial on how to install dynacraft ?

**Comment by shirubei** [comment]
@alexandrtsk  Attachment below shows versions of all python libs. Hope it help.  

[env_setting.zip](https://github.com/Doubiiu/DynamiCrafter/files/14627168/env_setting.zip)
