### ISSUE TITLE
Prompt-Image correspondence

### ISSUE THREAD

**Issue by kingnobro** [Doubiiu/DynamiCrafter#28]
In order to add a new prompt in `test_prompts.txt`, I need to first check the alphabetic order of the image filename, and insert it in the corresponding line? Any better way? Thanks.

**Comment by Doubiiu** [comment]
Hi. Thanks for your comments. 
"I need to first check the alphabetic order of the image filename, and insert it in the corresponding line" **EXACTLY**.
I think a better way is to reimplement the `load_prompts` and `load_data_prompts` in [inference.py](https://github.com/Doubiiu/DynamiCrafter/blob/main/scripts/evaluation/inference.py) and reformat the `test_prompts.txt` file.

For example, the prompt txt can be in the format of
"[filename]"+"[prompt]"
