### ISSUE TITLE
About AutoencoderKL

### ISSUE THREAD

**Issue by culeao** [Doubiiu/DynamiCrafter#30]
Did you train yourself to use AutoencoderKL in the latest version? Or still using the official SD AutoencoderKL weight? Have you ever tried training an AutoencoderKL from scratch?

**Comment by Doubiiu** [comment]
Hi. 
No, we didn't train or tune AutoencoderKL and we still use the official one. We haven't tried to train that from scratch. Thanks for your question, and we may try it by tuning AutoencoderKL in the future.
