### ISSUE TITLE
Frames sampling with different FPS

### ISSUE THREAD

**Issue by szxiangjn** [Doubiiu/DynamiCrafter#34]
Hi,

Thanks for your wonderful work! I don't quite understand the video frames sampling process. You mentioned in the paper that FPS is sampled between 5~30, so my understanding is that you first sample an FPS and then sample frames from a video by the FPS. Say like, we have a 10s video and an FPS of 16, how do you sample frames from the video?

Best

**Comment by Doubiiu** [comment]
Hi. We did that in a simple way: given a video clip in dataloader, we fetch its fps meta information and then sample frames with a stride `frame_stride` (e.g., 1-6), and then calculate the actual fps after sampling and pass this fps to the model.

**Comment by szxiangjn** [comment]
Thanks!
