### ISSUE TITLE
Question about charging in replicate

### ISSUE THREAD

**Issue by yvainePan** [Doubiiu/DynamiCrafter#4]
Hi, thanks for providing your model in Replicate, wonder if you will charge your model on it?

**Comment by Doubiiu** [comment]
Hi~ Thanks for your interest. The [Replicate demo](https://replicate.com/camenduru/dynami-crafter) is provided by [camenduru](https://twitter.com/camenduru) for free trial on A40 GPU and I will not charge that due to unaffordable cost.
