### ISSUE TITLE
AttributeError: 'VisionTransformer' object has no attribute 'input_patchnorm'

### ISSUE THREAD

**Issue by wimmerth** [Doubiiu/DynamiCrafter#40]
I get the following error message when I try to execute the method. Do you have any idea where this could be coming from?
```
"dynamicrafter/lvdm/modules/encoders/condition.py", line 339, in forward
    z = self.encode_with_vision_transformer(image)
"/dynamicrafter/lvdm/modules/encoders/condition.py", line 346, in encode_with_vision_transformer
    if self.model.visual.input_patchnorm:
AttributeError: 'VisionTransformer' object has no attribute 'input_patchnorm'
```

**Comment by Doubiiu** [comment]
Hi. Maybe the version of `open_clip` does not match? I know we set `open_clip_torch==2.22.0` in the requirements.txt, but could you try to install `open_clip_torch==2.17.1` and see if the issue can be fixed.

**Comment by wimmerth** [comment]
Hi, you're right, the `open_clip` version is probably the reason. I was using my own environment for development. However, it might be interesting for you to know that I was using `open-clip-torch==2.24.0`, so it seems they removed or renamed this. Thanks for your help, I'll close this issue.

**Comment by Doubiiu** [comment]
Thanks for letting me know this. Have a nice day~
