### ISSUE TITLE
1024模型是否不能运行在24G显存的GPU上？

### ISSUE THREAD

**Issue by didoll-john** [Doubiiu/DynamiCrafter#41]
我试了1024模型，不管把video_length减到多少，都是OOM
我看到其他网友在reddit和其他一些平台上问这个问题，但是没有人给予正面的回答。
希望作者能给出1024模型需要的显存大小，或者是否有办法降低显存的使用。
谢谢。

**Comment by Doubiiu** [comment]
请问你是用的local gradio demo吗，可以试一下最新的代码看看能否成功推理

**Comment by didoll-john** [comment]
可以成功推理了！感谢！

**Comment by OstwindDDR** [comment]
> 请问你是用的local gradio demo吗，可以试一下最新的代码看看能否成功推理

您好，我使用comfy ui进行生成，16G显存显示OOM，请问有办法解决吗

**Comment by Doubiiu** [comment]
> > 请问你是用的local gradio demo吗，可以试一下最新的代码看看能否成功推理
> 
> 您好，我使用comfy ui进行生成，16G显存显示OOM，请问有办法解决吗

Did you use the ComfyUI [here](https://github.com/kijai/ComfyUI-DynamiCrafterWrapper)? They have the pruned version of the model weights, which supports image animation at a resolution of 1024x576 using only 10GB memory.

**Comment by OstwindDDR** [comment]
> > > 请问你是用的local gradio demo吗，可以试一下最新的代码看看能否成功推理
> > 
> > 
> > 您好，我使用comfy ui进行生成，16G显存显示OOM，请问有办法解决吗
> 
> Did you use the ComfyUI [here](https://github.com/kijai/ComfyUI-DynamiCrafterWrapper)? They have the pruned version of the model weights, which supports image animation at a resolution of 1024x576 using only 10GB memory.

Thanks dude, it works!
