### ISSUE TITLE
License

### ISSUE THREAD

**Issue by fakerybakery** [Doubiiu/DynamiCrafter#43]
Hi,
Thanks for open sourcing! The license is Apache, however in the readme it says:
> We develop this repository for RESEARCH purposes, so it can only be used for personal/research/non-commercial purposes.

might it be possible to remove this since it is Apache licensed?
Thanks again for releasing this amazing work!

**Comment by Doubiiu** [comment]
Yeap. Thanks for pointing out. It has been modified.

**Comment by fakerybakery** [comment]
Thanks!
