### ISSUE TITLE
Any plan to release the training feature of this project?

### ISSUE THREAD

**Issue by dwanggit** [Doubiiu/DynamiCrafter#48]
Hi,

This is a really awesome project, and I really appreciate it. I am just wondering if you have any plan to release the training code for the open source community to do more experiments on it?

Thanks.

**Comment by Doubiiu** [comment]
Hi Thanks for your interest! Please see #26 here.
@dailingx is helping to reimplement the training scripts and he may make PR once it is done. Thanks again for your understanding.

**Comment by Doubiiu** [comment]
Hi @dwanggit .  I am cleaning up the code and plan to release it in the next few days.

**Comment by KytraScript** [comment]
> Hi @dwanggit . I am cleaning up the code and plan to release it in the next few days.
@Doubiiu 
Hey Doubiiu! Thanks for the hard work on this! I'm really eager to try a fine tune on DC. Any updates you could provide to the timeline of the training script release?

**Comment by Doubiiu** [comment]
Here you are. @dwanggit @KytraScript

**Comment by KytraScript** [comment]
> Here you are. @dwanggit @KytraScript

You're the best!
