### ISSUE TITLE
1024 model flashes gray

### ISSUE THREAD

**Issue by taylenhe20240219** [Doubiiu/DynamiCrafter#50]
Please tell me why the video I generated using the 1024 model flashes gray and the resolution is 576 1024.

**Comment by Doubiiu** [comment]
Can you show some examples here?

**Comment by taylenhe20240219** [comment]
![111111](https://github.com/Doubiiu/DynamiCrafter/assets/160470261/2e4be067-06a2-49a7-a7f8-62ff122d4bf0)

https://github.com/Doubiiu/DynamiCrafter/assets/160470261/a0106f18-2f73-4997-ae87-17703c212df6

**Just like this, the video and workflow are all in it

**Comment by Doubiiu** [comment]
Hi, Did you try to use the 1024_v1 model for interpolation?
Currently, we have released the 512_interp model for interpolation (resolution @512x320), while the 1024_v1 (1024x576) and 512_v1 (512x320) models are for single-image-to-video applications.

**Comment by taylenhe20240219** [comment]
![微信图片_20240327122358](https://github.com/Doubiiu/DynamiCrafter/assets/160470261/8d885107-bf81-4748-a4f4-0c03d6b46311)
Yes, I am currently using this 1024 model. Do you mean that the 1024 model does not support changes between pictures now? Only a single picture can be turned into a video

**Comment by Doubiiu** [comment]
> ![微信图片_20240327122358](https://private-user-images.githubusercontent.com/160470261/317123315-8d885107-bf81-4748-a4f4-0c03d6b46311.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1MTM5NTcsIm5iZiI6MTcxMTUxMzY1NywicGF0aCI6Ii8xNjA0NzAyNjEvMzE3MTIzMzE1LThkODg1MTA3LWJmODEtNDc0OC1hNGY0LTBjMDNkNmI0NjMxMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyN1QwNDI3MzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMzRhY2UzYTFhN2VmZWMzZWU2OTBhN2ExNzBhZjM2OWJkMjE2MjBlZGY1ODgyODk4NmQ0NmEyODJhZmU0YmQ1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.IaPqDIksplsUDCGJIXD_eVl1ck5aXyizKyfoFgDelNY) Yes, I am currently using this 1024 model. Do you mean that the 1024 model does not support changes between pictures now? Only a single picture can be turned into a video

Exactly.
As shown in the README, we have released the following models:
Image-to-Video: DynamiCrafter1024, DynamiCrafter512, DynamiCrafter256
Interpolation / looping: DynamiCrafter512_interp

**Comment by taylenhe20240219** [comment]
thank you!!!
