### ISSUE TITLE
generated frame question

### ISSUE THREAD

**Issue by PMPBinZhang** [Doubiiu/DynamiCrafter#54]
hello，thanks for your work，but I have a question here, how to make the generated frames start with the reference image, rather than the reference image that is the result of the middle of the generated frame，is there a parameter to control this?

**Comment by Doubiiu** [comment]
Not yet. We may add this control in the future.

**Comment by PMPBinZhang** [comment]
ok，looking forward. Thank you for your reply

| |
Wenwu Zhang
|
|
***@***.***
|
---- Replied Message ----
| From | ***@***.***> |
| Date | 04/01/2024 22:03 |
| To | Doubiiu/DynamiCrafter ***@***.***> |
| Cc | PMPBinZhang ***@***.***>,
Author ***@***.***> |
| Subject | Re: [Doubiiu/DynamiCrafter] generated frame question (Issue #54) |

Not yet. We may add this control in the future.
