### ISSUE TITLE
Question about UCF-101/MSRVTT evaluation in paper

### ISSUE THREAD

**Issue by wren93** [Doubiiu/DynamiCrafter#6]
Hi,

Thank you for sharing this great work. I'm interested in how you performed the evaluation on UCF-101 and MSR-VTT in the paper, in particular, how did you select the first frame to let the model condition on when generating the video and how did you select the real videos to compute FVD? My understanding is that we could randomly select a 16-frame video clip from the test videos and use this as the real video. dynamicrafter then generates a video based on the first frame of the selected video clip. This generated video is then compared against the real video. Is this the correct understanding? Thanks in advance.

**Comment by Doubiiu** [comment]
Hi Thanks for your interest. It is correct.
It is worth noting that we should use frame stride `s=3` to sample the 16-frame clips and use it as condition for image-to-video generation using DynamiCrafter. `s=3` approximately reflects a general motion speed (not to fast or too slow).

**Comment by wren93** [comment]
thanks for answering! May I also ask how many videos did you use to evaluate on UCF-101 and MSR-VTT? Is it 10k and 2990?

**Comment by Doubiiu** [comment]
We use 2048 samples for both datasets, as we have mentioned in section B.1 in the [Appendix](https://arxiv.org/pdf/2310.12190.pdf).

**Comment by wren93** [comment]
I see, thanks!

**Comment by hiteshK03** [comment]
Hi, following on the above discussion, can you tell how you selected the 2048 samples for both the datasets? Because on calculating FVD for the entire dataset of MSR-VTT i.e. on 2990 videos, I got a score of 328 which is more than the reported value. Therefore, I was curious to know, if I am doing something wrong here.

Thanks.
