### ISSUE TITLE
OSError: [Errno 101] Network is unreachable

### ISSUE THREAD

**Issue by jdfgfcvb** [Doubiiu/DynamiCrafter#62]
Hi, @Doubiiu I met an error when running python gradio_app.py --res 512 or sh scripts/run.sh 512:
OSError: [Errno 101] Network is unreachable
![11111](https://github.com/Doubiiu/DynamiCrafter/assets/123803838/4cbda241-0182-424a-96ca-152884ffee9b)
![22222](https://github.com/Doubiiu/DynamiCrafter/assets/123803838/36bc0d29-b036-4107-aa5a-a8ac3b2b52b4)

**Comment by Doubiiu** [comment]
Hi. It seems that your machine cannot access HuggingFace model due to some network problems.

**Comment by jdfgfcvb** [comment]
Yes, the problem has been resolved. Thank you

**Comment by EvanZouQ** [comment]
> Yes, the problem has been resolved. Thank you

Hi, could you tell how to solve this issue? Many thanks.
