### ISSUE TITLE
How Dynamicrafter achieve frame interpolation?

### ISSUE THREAD

**Issue by 0Godness** [Doubiiu/DynamiCrafter#64]
Hi, Dynamicrafter is a very nice work and has so many applications. I want to ask how Dynamicrafter achieve frame interpolation? Hoping for your reply!

**Comment by Doubiiu** [comment]
For the image-to-video/image animation application, we just feed a single image to the i2v model, while for interpolation, we feed both the starting image and ending image to the model and fine-tune the above i2v model with this new 'interpolation' setting.

**Comment by 0Godness** [comment]
> For the image-to-video/image animation application, we just feed a single image to the i2v model, while for interpolation, we feed both the starting image and ending image to the model and fine-tune the above i2v model with this new 'interpolation' setting.

Thanks for your reply! So, is it training process? I would like to ask what adjustments have been made to the training compared to the I2V training process.

**Comment by 0Godness** [comment]
Sorry to bother you again. How do you use the starting and ending image as the condition injection? And does it need to modify the Transformer Attention? Hoping for your reply!Thanks!~

**Comment by Doubiiu** [comment]
Hi. Sorry for the late reply. Actually you can see the frame interpolation mechanism from the code and paper, we don't have any special design for this. We just concat both frames to the noisy latent, and leave other frames as empty latent. Please check the code for the concrete operations.
