### ISSUE TITLE
Finetune

### ISSUE THREAD

**Issue by IranQin** [Doubiiu/DynamiCrafter#66]
Nice work! Do you have any plans to open source training code and scripts, I would like to try some fine-tuning.

**Comment by Doubiiu** [comment]
Hi Thanks for your interest! Please see #26  here.
@dailingx is helping to reimplement the training scripts and he may make PR once it is done. Thanks again for your understanding.

**Comment by Doubiiu** [comment]
@IranQin Hi. I am cleaning up the code and plan to release it in the next few days.

**Comment by yujiangpu20** [comment]
Thank you for the excellent work! Will the training code be released this week?

**Comment by Doubiiu** [comment]
Here you are. @IranQin @yujiangpu20
