### ISSUE TITLE
When the video (generative frame) interpolation will be available?

### ISSUE THREAD

**Issue by DomainFlag** [Doubiiu/DynamiCrafter#7]
https://github.com/Doubiiu/DynamiCrafter/blob/a8ce9e0ea22c63661ab22589160fb424e4f24cf6/scripts/evaluation/inference.py#L315C48-L315C78

**Comment by Doubiiu** [comment]
Hi Thanks for your interest! We are currently working diligently to improve the model's stability at a resolution of 320x512, which includes image animation and generative frame interpolation. We will release these models as soon as possible.

**Comment by DomainFlag** [comment]
Thanks, looking forward!

**Comment by Doubiiu** [comment]
😭Sorry for the late reply, we have released the generative frame interpolation and looping video generation model & their corresponding gradio demo. Have a try if you are still interested in them! @DomainFlag

> Hi Thanks for your interest! We are currently working diligently to improve the model's stability at a resolution of 320x512, which includes image animation and generative frame interpolation. We will release these models as soon as possible.
