### ISSUE TITLE
是否可以控制Camera,像stablevideo那样

### ISSUE THREAD

**Issue by ZeeLyn** [Doubiiu/DynamiCrafter#70]
![image](https://github.com/Doubiiu/DynamiCrafter/assets/17895675/41c077aa-6dee-43d1-8f17-bf17fddd7a94)

**Comment by Doubiiu** [comment]
No. Currently, DynamiCrafter is not equipped with this kind of camera control explicitly, but the text prompt with keywords like Zoom-in, rotating view, can somehow make it achieve camera control. It may need LoRA or adapter with additional training to achieve more explicit camera control.
