### ISSUE TITLE
Do you have any plans to release the interpolation training code?

### ISSUE THREAD

**Issue by wangqiang9** [Doubiiu/DynamiCrafter#72]
Hi, Thanks for your very helpful work!
Do you have any plans to release the video frame interpolation training code?

**Comment by k15201363625** [comment]
+1

**Comment by Doubiiu** [comment]
Hi. I will release the training code this month. Currently, I am too busy with other research projects. Thanks for your interest and patience.

**Comment by wangqiang9** [comment]
> Hi. I will release the training code this month. Currently, I am too busy with other research projects. Thanks for your interest and patience.

Thank you. Looking forward to it

**Comment by k15201363625** [comment]
> Hi. I will release the training code this month. Currently, I am too busy with other research projects. Thanks for your interest and patience.

Thank you. Looking forward to it

**Comment by QingqingSUN** [comment]
hello,first ,thank you for your great work on video generation。Recently,our team is currently attempting to train a high-resolution frame interpolation model.
 the motion/dynamic effect of the 1024 model we are training is significantly reduced compared to the motion/dynamic effect of the 512 model you published.
what factors or parameters might affect the model's motion/dynamic performance during training? thanks

**Comment by Doubiiu** [comment]
Done.
