### ISSUE TITLE
annotations of the constructed dataset 

### ISSUE THREAD

**Issue by eugenelyj** [Doubiiu/DynamiCrafter#73]
Nice work! Just curious how to get the annotations of the constructed dataset?

**Comment by eugenelyj** [comment]
@Doubiiu Hello

**Comment by Doubiiu** [comment]
Hi. We will release it soon, as I am currently busy with other research projects.

**Comment by Doubiiu** [comment]
Available now.

**Comment by eugenelyj** [comment]
@Doubiiu Thank you. I have one more question: the constructed dataset only covers 2.5/2.6M video clips, do you randomly choose from the full webvid or is it the result of filtering?

**Comment by Doubiiu** [comment]
They are filtered as described in the paper.

**Comment by eugenelyj** [comment]
Sorry, get it now. But how do you decide whether it is  Graphics/CGI content? By the caption or by the image content?

**Comment by Doubiiu** [comment]
Here I just use the ChatGPT to generate some keywords about the CGI/Graphics content and then filter those videos using caption only. A better way is to filter using image content.

**Comment by eugenelyj** [comment]
Thank you for your kindly reply. The last question...How do you decide the level of caption/video alignment? By Clip or other models?

**Comment by Doubiiu** [comment]
yeap, using CLIP following previous video generation works
