### ISSUE TITLE
Can you provide more information on the Story telling video generation?

### ISSUE THREAD

**Issue by cbokka** [Doubiiu/DynamiCrafter#80]
Hi, I'm struggling to find any code or details about this? https://github.com/Doubiiu/DynamiCrafter?tab=readme-ov-file#21-storytelling-video-generation-see-project-page-for-more-details. Can you pleae help me find more information about this, like the code etc.

**Comment by Doubiiu** [comment]
Actually, this is straightforward:
1. ask chatgpt for a story 
2. ask dalle3 to generate 4 shots (images) of that story
3. use dynamicrafter to animate each of the shots to generate videos
