### ISSUE TITLE
How to make the video start with the image I given?

### ISSUE THREAD

**Issue by bopan3** [Doubiiu/DynamiCrafter#87]
How to make the video start with the image I given? Currently the image I given seems to appear at the middle of the video.

**Comment by Doubiiu** [comment]
As stated in the paper, we employ random selection during the training process. Consequently, the location of the input frame in the generated videos is derived from the complex conditional distribution that the model has learned. You may need to fine-tune the model by fixing the conditional input image as the first frame of the videos.
