### ISSUE TITLE
how to generate prompts of custom videos

### ISSUE THREAD

**Issue by zhuyglx** [Doubiiu/DynamiCrafter#89]
Hello, thanks for your great job and open source. I want to ask if i will finetune model in my own dataset, I only have videos, any good video caption method I can use? thank you very much.

**Comment by Doubiiu** [comment]
We employed the image captioning tool [BLIP2](https://huggingface.co/spaces/Salesforce/BLIP2) throughout our experiments. Recently, we noticed that [VideoChat](https://github.com/OpenGVLab/Ask-Anything) and [VILA](https://github.com/Efficient-Large-Model/VILA) were adopted in [EasyAnimate](https://arxiv.org/pdf/2405.18991) for video captioning.

**Comment by zhuyglx** [comment]
> We employed the image captioning tool [BLIP2](https://huggingface.co/spaces/Salesforce/BLIP2) throughout our experiments. Recently, we noticed that [VideoChat](https://github.com/OpenGVLab/Ask-Anything) and [VILA](https://github.com/Efficient-Large-Model/VILA) were adopted in [EasyAnimate](https://arxiv.org/pdf/2405.18991) for video captioning.

thx very much
