### ISSUE TITLE
Will you release the code for training the interpolation model?

### ISSUE THREAD

**Issue by bobeovitvang** [Doubiiu/DynamiCrafter#91]
Hello,

First of all, I really appreciate your work. It has been a great help to me. I have reviewed your recent release of the training code for Image-to-Video Generation and found it truly impressive. Just a small concern: are you planning to release the code for **training interpolation** models? This is a fascinating field, and having access to the training code would allow me, as well as others, to delve deeper into it. 

Of course I will definitely use it for education and research purposes. Once again, thank you, and have a nice day.

**Comment by Doubiiu** [comment]
Yes, I will release it this weekend.

**Comment by motcapbovit** [comment]
I’m really thrilled to hear that! Thank you so much for your effort! Eagerly looking forward to the release.

**Comment by bobeovitvang** [comment]
What can I say more... Big thanks your incredible contribution and effort. I truly appreciate it!

> Yes, I will release it this weekend.

**Comment by Doubiiu** [comment]
Done

**Comment by motcapbovit** [comment]
Wowww 😲 Thank you very much for your effort and timely replies 💯💯
